substitutions:
  devicename: "homeiq-relay-x4"
  name: "HomeIQ Relay x4"
  project_name: "homeiq.relay-x4"
  project_version: "1.0"

esphome:
  name: "${devicename}"
  name_add_mac_suffix: true
  platform: ESP8266
  board: esp8285
  project:
    name: "${project_name}"
    version: "${project_version}"

api:

ota:

logger:

web_server:
  port: 80

wifi:
  ap: {} # This spawns an AP with the device name and mac address with no password.

captive_portal:

dashboard_import:
  package_import_url: github://SmarterHomeLife/esphome/homeiq-relay-x4.yaml

binary_sensor:
  - platform: status
    name: "${name} Status"

sensor:
  - platform: uptime
    name: "${name} Uptime Sensor"

  - platform: wifi_signal
    name: "${name} WiFi Signal"
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${name} IP Address"

switch:
  - platform: restart
    id: restart_switch
    name: "${name} Restart"

  - platform: gpio
    name: "${name} - 1"
    pin: GPIO16
    id: relay1

  - platform: gpio
    name: "${name} - 2"
    pin: GPIO14
    id: relay2

  - platform: gpio
    name: "${name} - 3"
    pin: GPIO12
    id: relay3

  - platform: gpio
    name: "${name} - 4"
    pin: GPIO13
    id: relay4

light:
  - platform: status_led
    name: "${name} Status LED"
    disabled_by_default: true
    pin:
      inverted: true
      number: GPIO5
